version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    volumes:
      - .:/var/www/html
    networks:
      - ci4net
    env_file:
      - .env

  webserver:
    image: nginx:stable
    container_name: ci4_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ci4net

  mysql:
    image: mysql:8.0
    container_name: ci4_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4db
      MYSQL_USER: ci4user
      MYSQL_PASSWORD: ci4pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci4net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - ci4net

volumes:
  db_data:

networks:
  ci4net:
    driver: bridge
